### ISSUE TITLE
Discord Rich Presence always showing

### ISSUE THREAD

**Issue by x4e** [UltimateLeaks/JByteMod-Reborn#3]
Discord Rich Presence seems to always show up regardless of your config

![image](https://user-images.githubusercontent.com/53862811/73931972-3606c700-48d1-11ea-83e8-4a797ed34a4f.png)

**Comment by x4e** [comment]
Temporary fix: Use recaf to insert a return at the start of each method in the discord class

**Comment by fee1-dead** [comment]
wow why was this closed it wasn't even fixed in the repo
